import type { INodeProperties } from 'n8n-workflow';

/**
 * Resource selector and operation dropdown properties.
 * Kept separate to reduce root description file size.
 */
export const coreNanoRPCProperties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Account',
				value: 'account',
				description: 'Access balances, history, and account state',
			},
			{
				name: 'Administration',
				value: 'administration',
				description: 'Administrative and debug utilities',
			},
			{
				name: 'Block',
				value: 'block',
				description: 'Inspect and create Nano blocks',
			},
			{
				name: 'Confirmation',
				value: 'confirmation',
				description: 'Review block confirmation details',
			},
			{
				name: 'Conversion',
				value: 'conversion',
				description: 'Convert between Nano and raw units',
			},
			{
				name: 'Key',
				value: 'keys',
				description: 'Generate and manage cryptographic keys',
			},
			{
				name: 'Ledger',
				value: 'ledger',
				description: 'Traverse ledger chains and frontiers',
			},
			{
				name: 'Network',
				value: 'network',
				description: 'Retrieve node and peer status',
			},
			{
				name: 'Representative',
				value: 'representative',
				description: 'Inspect representatives and delegators',
			},
			{
				name: 'Transaction',
				value: 'transaction',
				description: 'Send funds and manage pending blocks',
			},
			{
				name: 'Wallet',
				value: 'wallet',
				description: 'Manage wallet accounts',
			},
			{
				name: 'Work',
				value: 'work',
				description: 'Generate and manage proof-of-work',
			},
		],
		default: 'account',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['account'],
			},
		},
		options: [
			{
				name: 'Get Account Block Count',
				value: 'accountBlockCount',
				description:
					'Get the total number of blocks (transactions) that have been confirmed for a specific Nano account. Requires account address. Returns the block count as a number',
				action: 'Get account block count',
			},
			{
				name: 'Get Account From Public Key',
				value: 'getAccountFromPublicKey',
				description: 'Convert a public key to its corresponding Nano account address',
				action: 'Get account from public key',
			},
			{
				name: 'Get Account Info',
				value: 'accountInfo',
				description: 'Get detailed account information',
				action: 'Get account information',
			},
			{
				name: 'Get Account Key',
				value: 'accountKey',
				description:
					'Retrieve the public key (64 character hex string) associated with a Nano account address. Requires account address. Returns the public key used for cryptographic operations',
				action: 'Get account public key',
			},
			{
				name: 'Get Account Representative',
				value: 'accountRepresentative',
				description:
					'Get the current voting representative (delegate) for a Nano account. Requires account address. Returns representative account address',
				action: 'Get account representative',
			},
			{
				name: 'Get Account Weight',
				value: 'accountWeight',
				description:
					'Get the total voting weight delegated to a representative account in raw units. Requires account address. Returns voting weight',
				action: 'Get account weight',
			},
			{
				name: 'Get Accounts Balances',
				value: 'getAccountsBalances',
				description: 'Get balances for multiple Nano accounts in a single request',
				action: 'Get multiple accounts balances',
			},
			{
				name: 'Get Accounts Frontiers',
				value: 'getAccountsFrontiers',
				description: 'Get frontier (most recent) blocks for multiple accounts',
				action: 'Get accounts frontiers',
			},
			{
				name: 'Get Accounts Receivable',
				value: 'getAccountsReceivable',
				description: 'Get receivable transactions for multiple accounts with optional thresholds',
				action: 'Get accounts receivable',
			},
			{
				name: 'Get Accounts Representatives',
				value: 'getAccountsRepresentatives',
				description: 'Get the current voting representatives for multiple accounts',
				action: 'Get accounts representatives',
			},
			{
				name: 'Get Balance',
				value: 'balance',
				description: 'Get account balance',
				action: 'Get account balance',
			},
			{
				name: 'Get History',
				value: 'history',
				description: 'Get transaction history',
				action: 'Get transaction history',
			},
			{
				name: 'Get Receivable',
				value: 'receivable',
				description: 'List receivable (pending incoming) transactions for an account',
				action: 'Get receivable transactions',
			},
			{
				name: 'Validate Address',
				value: 'validate',
				description: 'Validate Nano address format',
				action: 'Validate a nano address',
			},
		],
		default: 'balance',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['transaction'] } },
		options: [
			{
				name: 'Check Receivable Exists',
				value: 'receivableExists',
				description: 'Check if a specific receivable block hash exists and is valid in the ledger',
				action: 'Check receivable exists',
			},
			{
				name: 'Epoch Upgrade',
				value: 'epochUpgrade',
				description: 'Perform an epoch upgrade on accounts to enable new protocol features',
				action: 'Epoch upgrade',
			},
			{
				name: 'Process Block',
				value: 'processBlock',
				description: 'Publish a signed block to the Nano network for processing and confirmation',
				action: 'Process and publish a block',
			},
			{
				name: 'Receive Pending',
				value: 'receive',
				description: 'Receive pending transactions',
				action: 'Receive pending transactions',
			},
			{
				name: 'Send Payment',
				value: 'send',
				description: 'Send Nano to another address',
				action: 'Send a nano payment',
			},
		],
		default: 'send',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['block'] } },
		options: [
			{
				name: 'Confirm Block',
				value: 'confirmBlock',
				description: 'Manually request active confirmation for a specific block hash',
				action: 'Confirm a block',
			},
			{
				name: 'Create Block',
				value: 'createBlock',
				description: 'Create a new signed block with specified parameters',
				action: 'Create block',
			},
			{
				name: 'Get Block Account',
				value: 'blockAccount',
				description: 'Retrieve the account address that created a specific block',
				action: 'Get block account',
			},
			{
				name: 'Get Block Count',
				value: 'blockCount',
				description: 'Get the total number of confirmed and unchecked blocks',
				action: 'Get block count',
			},
			{
				name: 'Get Block Hash',
				value: 'getBlockHash',
				description: 'Calculate the hash for a block given its JSON structure',
				action: 'Get block hash',
			},
			{
				name: 'Get Block Info',
				value: 'blockInfo',
				description: 'Get information about a specific block',
				action: 'Get block information',
			},
			{
				name: 'Get Blocks',
				value: 'getBlocks',
				description: 'Retrieve the JSON content of multiple blocks by providing their hashes',
				action: 'Get multiple blocks',
			},
			{
				name: 'Get Blocks Info',
				value: 'getBlocksInfo',
				description:
					'Get detailed information for multiple blocks including amounts and confirmations',
				action: 'Get multiple blocks info',
			},
		],
		default: 'blockInfo',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['wallet'] } },
		options: [
			{
				name: 'Add Key to Wallet',
				value: 'walletAdd',
				description: 'Add an existing private key to a wallet',
				action: 'Add key to wallet',
			},
			{
				name: 'Add Watch-Only',
				value: 'walletAddWatch',
				description: 'Add watch-only accounts to a wallet',
				action: 'Add watch only accounts',
			},
			{
				name: 'Change Password',
				value: 'passwordChange',
				description: 'Change the password for a wallet',
				action: 'Change wallet password',
			},
			{
				name: 'Change Wallet Seed',
				value: 'walletChangeSeed',
				description: 'Change the seed for a wallet',
				action: 'Change wallet seed',
			},
			{
				name: 'Check Wallet Locked',
				value: 'walletLocked',
				description: 'Check if a wallet is locked',
				action: 'Check wallet locked',
			},
			{
				name: 'Create Account',
				value: 'createAccount',
				description: 'Create new account in wallet',
				action: 'Create a new account',
			},
			{
				name: 'Create Multiple Accounts',
				value: 'accountsCreate',
				description: 'Create multiple accounts in a wallet at once',
				action: 'Create multiple accounts',
			},
			{
				name: 'Create Wallet',
				value: 'walletCreate',
				description: 'Create a new wallet',
				action: 'Create wallet',
			},
			{
				name: 'Destroy Wallet',
				value: 'walletDestroy',
				description: 'Destroy a wallet',
				action: 'Destroy wallet',
			},
			{
				name: 'Enter Password',
				value: 'passwordEnter',
				description: 'Enter password to unlock a wallet',
				action: 'Unlock wallet with password',
			},
			{
				name: 'Export Wallet',
				value: 'walletExport',
				description: 'Export wallet as JSON',
				action: 'Export wallet',
			},
			{
				name: 'Get Account Work',
				value: 'workGet',
				description: 'Get cached work for an account',
				action: 'Get account work',
			},
			{
				name: 'Get Receive Minimum',
				value: 'receiveMinimum',
				description: 'Get the minimum receive threshold',
				action: 'Get receive minimum',
			},
			{
				name: 'Get Wallet Balances',
				value: 'walletBalances',
				description: 'Get balances for all accounts in a wallet',
				action: 'Get wallet balances',
			},
			{
				name: 'Get Wallet Frontiers',
				value: 'walletFrontiers',
				description: 'Get frontiers for all accounts in a wallet',
				action: 'Get wallet frontiers',
			},
			{
				name: 'Get Wallet History',
				value: 'walletHistory',
				description: 'Get transaction history for a wallet',
				action: 'Get wallet history',
			},
			{
				name: 'Get Wallet Info',
				value: 'walletInfo',
				description: 'Get wallet information including balance sum',
				action: 'Get wallet info',
			},
			{
				name: 'Get Wallet Ledger',
				value: 'walletLedger',
				description: 'Get ledger for all accounts in a wallet',
				action: 'Get wallet ledger',
			},
			{
				name: 'Get Wallet Receivable',
				value: 'walletReceivable',
				description: 'Get receivable blocks for a wallet',
				action: 'Get wallet receivable',
			},
			{
				name: 'Get Wallet Representative',
				value: 'walletRepresentative',
				description: 'Get wallet default representative',
				action: 'Get wallet representative',
			},
			{
				name: 'Get Wallet Work',
				value: 'walletWorkGet',
				description: 'Get cached work for a wallet',
				action: 'Get wallet work',
			},
			{
				name: 'List Accounts',
				value: 'listAccounts',
				description: 'List all accounts in wallet',
				action: 'List wallet accounts',
			},
			{
				name: 'Lock Wallet',
				value: 'walletLock',
				description: 'Lock a wallet',
				action: 'Lock wallet',
			},
			{
				name: 'Move Accounts',
				value: 'accountMove',
				description: 'Move accounts from one wallet to another',
				action: 'Move accounts between wallets',
			},
			{
				name: 'Remove Account',
				value: 'accountRemove',
				description: 'Remove an account from a wallet',
				action: 'Remove account from wallet',
			},
			{
				name: 'Republish Wallet Blocks',
				value: 'walletRepublish',
				description: 'Republish blocks for accounts in a wallet',
				action: 'Republish wallet blocks',
			},
			{
				name: 'Search Receivable',
				value: 'searchReceivable',
				description: 'Search for receivable blocks in a wallet',
				action: 'Search receivable blocks',
			},
			{
				name: 'Search Receivable All',
				value: 'searchReceivableAll',
				description: 'Search for receivable blocks in all wallets',
				action: 'Search all receivable blocks',
			},
			{
				name: 'Set Account Representative',
				value: 'accountRepresentativeSet',
				description: 'Set the representative for an account in a wallet',
				action: 'Set account representative',
			},
			{
				name: 'Set Account Work',
				value: 'workSet',
				description: 'Set cached work for an account',
				action: 'Set account work',
			},
			{
				name: 'Set Receive Minimum',
				value: 'receiveMinimumSet',
				description: 'Set the minimum receive threshold',
				action: 'Set receive minimum',
			},
			{
				name: 'Set Wallet Representative',
				value: 'walletRepresentativeSet',
				description: 'Set wallet representative for all accounts',
				action: 'Set wallet representative',
			},
			{
				name: 'Validate Password',
				value: 'passwordValid',
				description: 'Check if wallet password is valid',
				action: 'Validate wallet password',
			},
			{
				name: 'Wallet Contains',
				value: 'walletContains',
				description: 'Check if a wallet contains an account',
				action: 'Check wallet contains account',
			},
		],
		default: 'createAccount',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['ledger'] } },
		options: [
			{
				name: 'Get Chain',
				value: 'getChain',
				description: 'Get the block chain sequence starting from a specific block hash',
				action: 'Get block chain',
			},
			{
				name: 'Get Frontier Count',
				value: 'getFrontierCount',
				description: 'Get the total count of frontier blocks in the ledger',
				action: 'Get frontier count',
			},
			{
				name: 'Get Frontiers',
				value: 'getFrontiers',
				description: 'Get frontier blocks for accounts starting from a specific account address',
				action: 'Get frontiers',
			},
			{
				name: 'Get Ledger',
				value: 'getLedger',
				description:
					'Get ledger information including balances and block data starting from an account',
				action: 'Get ledger info',
			},
			{
				name: 'Get Successors',
				value: 'getSuccessors',
				description: 'Get successor blocks that follow a specific block hash',
				action: 'Get successors',
			},
			{
				name: 'Get Unopened',
				value: 'getUnopened',
				description: 'Get accounts that have receivable transactions but have never been opened',
				action: 'Get unopened accounts',
			},
		],
		default: 'getLedger',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['network'] } },
		options: [
			{
				name: 'Get Available Supply',
				value: 'getAvailableSupply',
				description: 'Get the total available supply of Nano in circulation',
				action: 'Get available supply',
			},
			{
				name: 'Get Node ID',
				value: 'getNodeId',
				description: 'Get the unique node ID key pair for this Nano node',
				action: 'Get node ID',
			},
			{
				name: 'Get Node Version',
				value: 'version',
				description: 'Get the Nano node software and protocol versions',
				action: 'Get node version',
			},
			{
				name: 'Get Peers',
				value: 'getPeers',
				description: 'List all currently connected peer nodes in the Nano network',
				action: 'Get peers',
			},
			{
				name: 'Get Representatives',
				value: 'getRepresentatives',
				description: 'Get a list of known voting representatives with their weights',
				action: 'Get representatives',
			},
			{
				name: 'Get Representatives Online',
				value: 'representativesOnline',
				description: 'List all voting representatives that are currently online',
				action: 'Get online representatives',
			},
			{
				name: 'Get Telemetry',
				value: 'getTelemetry',
				description: 'Get comprehensive telemetry data from the node',
				action: 'Get telemetry',
			},
			{
				name: 'Get Uptime',
				value: 'getUptime',
				description: 'Get the uptime of the Nano node in seconds',
				action: 'Get node uptime',
			},
			{
				name: 'Keepalive',
				value: 'keepalive',
				description: 'Send a keepalive packet to a specific peer to maintain connection',
				action: 'Send keepalive',
			},
			{
				name: 'Populate Backlog',
				value: 'populateBacklog',
				description: 'Populate the bootstrap backlog priority queue for faster synchronization',
				action: 'Populate backlog',
			},
			{
				name: 'Republish',
				value: 'republish',
				description: 'Republish blocks starting from a specific hash to ensure propagation',
				action: 'Republish blocks',
			},
		],
		default: 'version',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['confirmation'] } },
		options: [
			{
				name: 'Get Confirmation Active',
				value: 'getConfirmationActive',
				description: 'Get blocks currently being actively confirmed by the network',
				action: 'Get confirmation active',
			},
			{
				name: 'Get Confirmation History',
				value: 'getConfirmationHistory',
				description: 'Get recent confirmation history with optional block filtering',
				action: 'Get confirmation history',
			},
			{
				name: 'Get Confirmation Info',
				value: 'getConfirmationInfo',
				description: 'Get detailed confirmation status and voting information for a block',
				action: 'Get confirmation info',
			},
			{
				name: 'Get Confirmation Quorum',
				value: 'getConfirmationQuorum',
				description: 'Get quorum information for block confirmations including peer weights',
				action: 'Get confirmation quorum',
			},
			{
				name: 'Get Election Statistics',
				value: 'getElectionStatistics',
				description: 'Get statistics about active and recently completed elections',
				action: 'Get election statistics',
			},
		],
		default: 'getConfirmationInfo',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['work'] } },
		options: [
			{
				name: 'Add Work Peer',
				value: 'addWorkPeer',
				description: 'Add a work peer node for distributed proof-of-work generation',
				action: 'Add work peer',
			},
			{
				name: 'Cancel Work',
				value: 'cancelWork',
				description: 'Cancel an ongoing proof-of-work generation task for a block hash',
				action: 'Cancel work',
			},
			{
				name: 'Clear Work Peers',
				value: 'clearWorkPeers',
				description: 'Remove all configured work peers from the distributed PoW system',
				action: 'Clear work peers',
			},
			{
				name: 'Generate Work',
				value: 'generateWork',
				description: 'Generate proof-of-work for a block hash',
				action: 'Generate work',
			},
			{
				name: 'Get Work Peers',
				value: 'getWorkPeers',
				description: 'List all configured work peer nodes',
				action: 'Get work peers',
			},
			{
				name: 'Validate Work',
				value: 'validateWork',
				description: 'Validate if a proof-of-work value meets the difficulty threshold',
				action: 'Validate work',
			},
		],
		default: 'generateWork',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['keys'] } },
		options: [
			{
				name: 'Create Key',
				value: 'createKey',
				description: 'Generate a new random cryptographic keypair',
				action: 'Create new keypair',
			},
			{
				name: 'Sign Block',
				value: 'signBlock',
				description: 'Sign a block or hash using a private key or wallet account (v18.0+)',
				action: 'Sign block or hash',
			},
			{
				name: 'Expand Key',
				value: 'expandKey',
				description: 'Derive the public key and Nano account address from a private key',
				action: 'Expand private key',
			},
			{
				name: 'Get Deterministic Key',
				value: 'getDeterministicKey',
				description: 'Generate a deterministic keypair from a seed and index',
				action: 'Get deterministic key',
			},
		],
		default: 'createKey',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['representative'] } },
		options: [
			{
				name: 'Get Delegators',
				value: 'delegators',
				description: 'Get all accounts that delegate their voting weight to a representative',
				action: 'Get delegators',
			},
			{
				name: 'Get Delegators Count',
				value: 'delegatorsCount',
				description: 'Get the total count of accounts delegating to a representative',
				action: 'Get delegators count',
			},
		],
		default: 'delegators',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['administration'] } },
		options: [
			{
				name: 'Bootstrap',
				value: 'bootstrap',
				description: 'Bootstrap the node ledger from a specific peer',
				action: 'Bootstrap node',
			},
			{
				name: 'Bootstrap Any',
				value: 'bootstrapAny',
				description: 'Bootstrap the node ledger from any available peer automatically',
				action: 'Bootstrap any',
			},
			{
				name: 'Bootstrap Lazy',
				value: 'bootstrapLazy',
				description: 'Perform lazy bootstrap starting from a specific block hash',
				action: 'Bootstrap lazy',
			},
			{
				name: 'Clear Stats',
				value: 'clearStats',
				description: 'Clear all collected node statistics and reset counters',
				action: 'Clear stats',
			},
			{
				name: 'Clear Unchecked',
				value: 'clearUnchecked',
				description: 'Clear all unchecked blocks from the database',
				action: 'Clear unchecked',
			},
			{
				name: 'Get Bootstrap Priorities',
				value: 'getBootstrapPriorities',
				description: 'Get the current bootstrap priority queue for synchronization',
				action: 'Get bootstrap priorities',
			},
			{
				name: 'Get Bootstrap Status',
				value: 'getBootstrapStatus',
				description: 'Get the current status of the bootstrap process',
				action: 'Get bootstrap status',
			},
			{
				name: 'Get Database Txn Tracker',
				value: 'getDatabaseTxnTracker',
				description: 'Get database transaction tracking information for debugging',
				action: 'Get database txn tracker',
			},
			{
				name: 'Get Stats',
				value: 'getStats',
				description: 'Get detailed node statistics including counters, samples, or objects',
				action: 'Get node stats',
			},
			{
				name: 'Get Unchecked',
				value: 'getUnchecked',
				description: 'Get unchecked blocks that have been received but not validated',
				action: 'Get unchecked blocks',
			},
			{
				name: 'Get Unchecked Block',
				value: 'getUncheckedBlock',
				description: 'Get a specific unchecked block by its hash',
				action: 'Get unchecked block',
			},
			{
				name: 'Get Unchecked Keys',
				value: 'getUncheckedKeys',
				description: 'List unchecked block keys with optional pagination',
				action: 'Get unchecked keys',
			},
			{
				name: 'Reset Bootstrap',
				value: 'resetBootstrap',
				description: 'Reset the bootstrap process and clear the queue',
				action: 'Reset bootstrap',
			},
			{
				name: 'Stop Node',
				value: 'stopNode',
				description: 'Safely shutdown the Nano node',
				action: 'Stop node',
			},
		],
		default: 'bootstrap',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['conversion'] } },
		options: [
			{
				name: 'Nano to Raw (RPC)',
				value: 'nanoToRawRPC',
				description: 'Convert Nano amount to raw units (1 NANO = 10^30 raw) via RPC call',
				action: 'Convert nano to raw',
			},
			{
				name: 'Raw to Nano (RPC)',
				value: 'rawToNanoRPC',
				description: 'Convert raw units to Nano amount via RPC call',
				action: 'Convert raw to nano',
			},
		],
		default: 'nanoToRawRPC',
	},
];
